version: '3'
services:
  db:
    image: postgres
    ports:
      - 65433:5432
    environment:
      POSTGRES_PASSWORD: example
    #    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=pg_log -c log_statement=all
    volumes:
      - stock_data_postgres:/var/lib/postgresql/data
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - 63799:6379
volumes:
  stock_data_postgres:


