# Generated by Django 3.1.7 on 2021-09-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPortfolioStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(db_index=True, max_length=200)),
                ('portfolio_stats', models.JSONField()),
            ],
        ),
    ]
