# Generated by Django 3.1.7 on 2021-04-04 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.IntegerField(max_length=10)),
                ('symbol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dstype', models.CharField(choices=[('TD_AMERITRADE', 'TD Ameritrade'), ('QUANDL', 'Quandl'), ('SIMFIN', 'Simfin'), ('ALPHAVANTAGE', 'AlphaVantage'), ('NEWS_API_ORG', 'News API.org'), ('TWITTER', 'Twitter')], default='ALPHAVANTAGE', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('low', models.DecimalField(decimal_places=4, max_digits=13)),
                ('dividend_amount', models.DecimalField(decimal_places=4, max_digits=13)),
                ('adjusted_close', models.DecimalField(decimal_places=4, max_digits=13)),
                ('open', models.DecimalField(decimal_places=4, max_digits=13)),
                ('split_coefficient', models.DecimalField(decimal_places=4, max_digits=13)),
                ('close', models.DecimalField(decimal_places=4, max_digits=13)),
                ('high', models.DecimalField(decimal_places=4, max_digits=13)),
                ('volume', models.BigIntegerField(max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='symbolprice',
            constraint=models.UniqueConstraint(fields=('symbol', 'date_time'), name='symbol_prices_symbol_date_time_uindex'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasourcecredential',
            name='datasource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stonksconfig.datasource'),
        ),
        migrations.AddField(
            model_name='datasourcecredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='apirequest',
            constraint=models.UniqueConstraint(fields=('request_date', 'symbol'), name='request_date_symbol_unique'),
        ),
    ]
