# Generated by Django 3.1.7 on 2021-04-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonksconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='stonksconfig.portfolio')),
            ],
        ),
    ]
