# Generated by Django 3.1.7 on 2021-03-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonksconfig', '0002_auto_20210328_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stonksconfig.datasource')),
            ],
        ),
    ]
