# Generated by Django 3.1.7 on 2021-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonksconfig', '0002_portfoliosymbol'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apirequest',
            name='request_date_symbol_unique',
        ),
        migrations.AddField(
            model_name='apirequest',
            name='dstype',
            field=models.CharField(choices=[('TD_AMERITRADE', 'TD Ameritrade'), ('QUANDL', 'Quandl'), ('SIMFIN', 'Simfin'), ('ALPHAVANTAGE', 'AlphaVantage'), ('NEWS_API_ORG', 'News API.org'), ('TWITTER', 'Twitter')], default='ALPHAVANTAGE', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='apirequest',
            constraint=models.UniqueConstraint(fields=('request_date', 'symbol', 'dstype'), name='request_date_symbol_type_unique'),
        ),
    ]
